index 다루는법

pandas는 행을 index, 열을 columns 라고 부름

사실 둘 다 index임.

행의 index를 index, 열의 index를 columns라고 부름

index 다루는 법 이라는건, 행 다루는게 아니라 행과 열 둘 다를 말함.

In [1]:
import pandas as pd
df1 = pd.DataFrame([["파이전자", 20, 30, 30, 40, "반도체"],
                   ["썬닉스", 100, 90, 80, 100, "반도체"],
                   ["판다센", 300, 320, 340, 0, "게임"],
                   ["스마블", 0, 450, 300, 300, "게임"]],
                  columns=["종목", "A팀", "B팀", "C팀", "D팀", "분류"])
s1 = pd.Series([35000, 10000, 2000, 5000], index=list(df1["종목"]))
df2 = df1.set_index("종목").iloc[:,:4].mul(s1, axis=0)
df2 = df2.reindex(["D팀", "C팀", "B팀", "A팀", "분류"], axis=1).reset_index()
df2["분류"] = df1["분류"]

In [2]:
df1

     종목   A팀   B팀   C팀   D팀   분류
0  파이전자   20   30   30   40  반도체
1   썬닉스  100   90   80  100  반도체
2   판다센  300  320  340    0   게임
3   스마블    0  450  300  300   게임

In [4]:
list(df1.index)

[0, 1, 2, 3]

In [5]:
df1.columns

Index(['종목', 'A팀', 'B팀', 'C팀', 'D팀', '분류'], dtype='object')

In [9]:
df1.set_index("종목")

       A팀   B팀   C팀   D팀   분류
종목
파이전자   20   30   30   40  반도체
썬닉스   100   90   80  100  반도체
판다센   300  320  340    0   게임
스마블     0  450  300  300   게임

In [10]:
df1.set_index(["종목","분류"])

           A팀   B팀   C팀   D팀
종목   분류
파이전자 반도체   20   30   30   40
썬닉스  반도체  100   90   80  100
판다센  게임   300  320  340    0
스마블  게임     0  450  300  300

In [11]:
df1.set_index(["종목","분류"], drop=False)

            종목   A팀   B팀   C팀   D팀   분류
종목   분류
파이전자 반도체  파이전자   20   30   30   40  반도체
썬닉스  반도체   썬닉스  100   90   80  100  반도체
판다센  게임    판다센  300  320  340    0   게임
스마블  게임    스마블    0  450  300  300   게임

In [12]:
df1.set_index(["종목","분류"], append=True)

             A팀   B팀   C팀   D팀
  종목   분류
0 파이전자 반도체   20   30   30   40
1 썬닉스  반도체  100   90   80  100
2 판다센  게임   300  320  340    0
3 스마블  게임     0  450  300  300

In [14]:
df3 = df1.loc[ df1["종목"] != "판다센" ]
df3

     종목   A팀   B팀   C팀   D팀   분류
0  파이전자   20   30   30   40  반도체
1   썬닉스  100   90   80  100  반도체
3   스마블    0  450  300  300   게임

In [15]:
df3.reset_index()

   index    종목   A팀   B팀   C팀   D팀   분류
0      0  파이전자   20   30   30   40  반도체
1      1   썬닉스  100   90   80  100  반도체
2      3   스마블    0  450  300  300   게임

In [16]:
df3.reset_index(drop=True)

     종목   A팀   B팀   C팀   D팀   분류
0  파이전자   20   30   30   40  반도체
1   썬닉스  100   90   80  100  반도체
2   스마블    0  450  300  300   게임

In [17]:
df3.T

       0    1    3
종목  파이전자  썬닉스  스마블
A팀    20  100    0
B팀    30   90  450
C팀    30   80  300
D팀    40  100  300
분류   반도체  반도체   게임

In [18]:
df3.T.reset_index()

  index     0    1    3
0    종목  파이전자  썬닉스  스마블
1    A팀    20  100    0
2    B팀    30   90  450
3    C팀    30   80  300
4    D팀    40  100  300
5    분류   반도체  반도체   게임

In [20]:
df3.T.reset_index(drop=True).T

      0    1    2    3    4    5
0  파이전자   20   30   30   40  반도체
1   썬닉스  100   90   80  100  반도체
3   스마블    0  450  300  300   게임

In [22]:
df1.reindex(columns=["종목", "B팀", "A팀", "D팀", "C팀", "분류"])

     종목   B팀   A팀   D팀   C팀   분류
0  파이전자   30   20   40   30  반도체
1   썬닉스   90  100  100   80  반도체
2   판다센  320  300    0  340   게임
3   스마블  450    0  300  300   게임

In [24]:
df2

     종목       D팀       C팀       B팀       A팀   분류
0  파이전자  1400000  1050000  1050000   700000  반도체
1   썬닉스  1000000   800000   900000  1000000  반도체
2   판다센        0   680000   640000   600000   게임
3   스마블  1500000  1500000  2250000        0   게임

In [26]:
df1.reindex(columns = df2.columns)

     종목   D팀   C팀   B팀   A팀   분류
0  파이전자   40   30   30   20  반도체
1   썬닉스  100   80   90  100  반도체
2   판다센    0  340  320  300   게임
3   스마블  300  300  450    0   게임

In [27]:
df1.reindex(columns=["B팀", "A팀", "A팀", "E팀"])

    B팀   A팀   A팀  E팀
0   30   20   20 NaN
1   90  100  100 NaN
2  320  300  300 NaN
3  450    0    0 NaN

In [29]:
df1.reindex(columns=["B팀", "A팀", "A팀", "E팀"], fill_value=0)

    B팀   A팀   A팀  E팀
0   30   20   20   0
1   90  100  100   0
2  320  300  300   0
3  450    0    0   0

In [30]:
df1

     종목   A팀   B팀   C팀   D팀   분류
0  파이전자   20   30   30   40  반도체
1   썬닉스  100   90   80  100  반도체
2   판다센  300  320  340    0   게임
3   스마블    0  450  300  300   게임

In [32]:
df1.rename(columns={"A팀":"AAA팀"})

     종목  AAA팀   B팀   C팀   D팀   분류
0  파이전자    20   30   30   40  반도체
1   썬닉스   100   90   80  100  반도체
2   판다센   300  320  340    0   게임
3   스마블     0  450  300  300   게임

In [33]:
df2

     종목       D팀       C팀       B팀       A팀   분류
0  파이전자  1400000  1050000  1050000   700000  반도체
1   썬닉스  1000000   800000   900000  1000000  반도체
2   판다센        0   680000   640000   600000   게임
3   스마블  1500000  1500000  2250000        0   게임

In [37]:
df2.sort_index(axis=1)

        A팀       B팀       C팀       D팀   분류    종목
0   700000  1050000  1050000  1400000  반도체  파이전자
1  1000000   900000   800000  1000000  반도체   썬닉스
2   600000   640000   680000        0   게임   판다센
3        0  2250000  1500000  1500000   게임   스마블