sort_values 를 이용한 정렬

In [2]:
import pandas as pd
a1 = [60, 84, 80, 70, 19]
a2 = [77, 62, 95, 85, 17]
a3 = [61, 97, 72, 67, 15]
a4 = [75, 65, 95, 51, 18]
cols = ["국어", "영어", "수학", "과학", "나이"]
df = pd.DataFrame([a1, a2, a3, a4], index=list("ABCD"), columns=cols)

In [3]:
df

   국어  영어  수학  과학  나이
A  60  84  80  70  19
B  77  62  95  85  17
C  61  97  72  67  15
D  75  65  95  51  18

In [4]:
df.sort_values("국어")

   국어  영어  수학  과학  나이
A  60  84  80  70  19
C  61  97  72  67  15
D  75  65  95  51  18
B  77  62  95  85  17

In [5]:
df.sort_values("국어", ascending=False)

   국어  영어  수학  과학  나이
B  77  62  95  85  17
D  75  65  95  51  18
C  61  97  72  67  15
A  60  84  80  70  19

In [6]:
df.sort_values(["수학","국어"])

   국어  영어  수학  과학  나이
C  61  97  72  67  15
A  60  84  80  70  19
D  75  65  95  51  18
B  77  62  95  85  17

In [7]:
 df.sort_values(["수학","나이"], ascending=[0, 1])

   국어  영어  수학  과학  나이
B  77  62  95  85  17
D  75  65  95  51  18
A  60  84  80  70  19
C  61  97  72  67  15

In [8]:
 df.sort_values(["수학","나이"], ascending=[0, 0])

   국어  영어  수학  과학  나이
D  75  65  95  51  18
B  77  62  95  85  17
A  60  84  80  70  19
C  61  97  72  67  15