broadcasting 과 연산

넘파이 - 행렬 연산

판다스 - 같은 인덱스와 컬럼끼리 연산. 라벨이 중요.

데이터프레임과 시리즈의 연산에서는 시리즈를 브로드캐스팅해서 연산

다만 시리즈를 데이터프레임으로 브로드캐스팅 한 후에도 인덱스와 컬럼 기준으로 연산

In [1]:
import pandas as pd
a1 = [[1,2,3], [4,5,6,], [7,8,9]]
df1 = pd.DataFrame(a1, columns=list("ABC"), index=list("가나다"))
df2 = df1.reindex(columns=list("BCA"), index=list("나다가")).copy()
sr1 = df1.loc["가"]
df3 = df1.iloc[:2,:2]

In [2]:
df1

   A  B  C
가  1  2  3
나  4  5  6
다  7  8  9

In [3]:
df2

   B  C  A
나  5  6  4
다  8  9  7
가  2  3  1

In [4]:
df3

   A  B
가  1  2
나  4  5

In [5]:
sr1

A    1
B    2
C    3
Name: 가, dtype: int64

In [6]:
df1*df1

    A   B   C
가   1   4   9
나  16  25  36
다  49  64  81

In [7]:
df1 + df2

    A   B   C
가   2   4   6
나   8  10  12
다  14  16  18

In [8]:
df1 + df3

     A     B   C
가  2.0   4.0 NaN
나  8.0  10.0 NaN
다  NaN   NaN NaN

In [12]:
df1.add(df3, fill_value=0) #fill_value : 맞는 인덱스나 컬럼이 없을 때 NaN 대신 넣을 숫자. 해당 숫자를 넣어서 df1의 데이터와 합해서 넣어줌.

     A     B    C
가  2.0   4.0  3.0
나  8.0  10.0  6.0
다  7.0   8.0  9.0

In [13]:
df1.add(df3, fill_value=100)

       A      B      C
가    2.0    4.0  103.0
나    8.0   10.0  106.0
다  107.0  108.0  109.0

In [14]:
df1 + sr1

   A   B   C
가  2   4   6
나  5   7   9
다  8  10  12

In [16]:
df1.add(sr1, axis=1)

   A   B   C
가  2   4   6
나  5   7   9
다  8  10  12

In [17]:
df1.add(sr1, axis=0)

    A   B   C
A NaN NaN NaN
B NaN NaN NaN
C NaN NaN NaN
가 NaN NaN NaN
나 NaN NaN NaN
다 NaN NaN NaN