In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame([[3,2,5], [10,0,2],[6,5,3]], columns=["사과", "자두", "포도"], index=["이성계", "김유신", "이순신"])
s1 = df1["사과"]

In [ ]:
df1

     사과  자두  포도
이성계   3   2   5
김유신  10   0   2
이순신   6   5   3

In [ ]:
s1

이성계     3
김유신    10
이순신     6
Name: 사과, dtype: int64

In [ ]:
df1.values

array([[ 3,  2,  5],
       [10,  0,  2],
       [ 6,  5,  3]])

In [ ]:
df1.index

Index(['이성계', '김유신', '이순신'], dtype='object')

In [ ]:
df1.columns

Index(['사과', '자두', '포도'], dtype='object')

In [ ]:
df1.values > 3

array([[False, False,  True],
       [ True, False, False],
       [ True,  True, False]])

In [ ]:
df1 > 3

        사과     자두     포도
이성계  False  False   True
김유신   True  False  False
이순신   True   True  False

In [ ]:
s1 > 3

이성계    False
김유신     True
이순신     True
Name: 사과, dtype: bool

In [ ]:
pd.read_excel("score_tkk.xlsx")

    이름   국어  영어  수학
0  태현준  100  20  50
1  김지민   30  50  60
2  김지철   70  80  90

In [ ]:
pd.read_excel("score_tkk.xlsx").set_index("이름")

      국어  영어  수학
이름
태현준  100  20  50
김지민   30  50  60
김지철   70  80  90

In [ ]:
pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], index = ["가", "나", "다"], columns=["아", "야", "어"])

   아  야  어
가  1  2  3
나  4  5  6
다  7  8  9

In [ ]:
pd.Series([1, 2, 3], index = ["가", "나", "다"])

가    1
나    2
다    3
dtype: int64