boolean indexing

true/false 배열을 만들어서 이를 이용해서 인덱싱

In [1]:
import pandas as pd
import numpy as np
a1 = [60, 84, 80, 70, "문예부"]
a2 = [77, 62, 95, 85, "과학부"]
a3 = [61, 97, 72, np.nan, "농구부"]
a4 = [75, 65, 95, np.nan, "다도부"]
cols = ["국어", "영어", "수학", "과학", "소속"]
b1 = ["문예부", "과학부", "다도부"]
df = pd.DataFrame([a1, a2, a3, a4], index=list("ABCD"), columns=cols)

In [2]:
df

   국어  영어  수학    과학   소속
A  60  84  80  70.0  문예부
B  77  62  95  85.0  과학부
C  61  97  72   NaN  농구부
D  75  65  95   NaN  다도부

In [16]:
df.loc[["A"]]

   국어  영어  수학    과학   소속
A  60  84  80  70.0  문예부

In [15]:
df.loc[:,["영어"]]

   영어
A  84
B  62
C  97
D  65

In [17]:
filter1 = df["영어"] > 80
filter1

A     True
B    False
C     True
D    False
Name: 영어, dtype: bool

In [22]:
df.loc[filter1]

   국어  영어  수학    과학   소속
A  60  84  80  70.0  문예부
C  61  97  72   NaN  농구부

In [23]:
df.loc[filter1, "국어" : "과학"]

   국어  영어  수학    과학
A  60  84  80  70.0
C  61  97  72   NaN

In [24]:
filter2 = df["국어"] > 60
filter3 = df["수학"] > 75
df.loc[filter2 & filter3]

   국어  영어  수학    과학   소속
B  77  62  95  85.0  과학부
D  75  65  95   NaN  다도부

In [40]:
# 필터4 : 과학 시험을 쳤다. 쳤으면 true 안쳤으면 false
filter4 = df["과학"].isnull()

In [41]:
df.loc[filter4]

   국어  영어  수학  과학   소속
C  61  97  72 NaN  농구부
D  75  65  95 NaN  다도부

In [42]:
df.loc[~filter4]

   국어  영어  수학    과학   소속
A  60  84  80  70.0  문예부
B  77  62  95  85.0  과학부

In [43]:
# 과학 시험을 안쳤더라도 수학 시험이 90점이 넘으면 면제라고 하면? -> 필터5 : 과학 시험을 쳤다 or 수학이 90 넘는다
filter5 = (~df["과학"].isnull()) | (df["수학"] > 90)
filter5

A     True
B     True
C    False
D     True
dtype: bool

In [44]:
df.loc[filter5]

   국어  영어  수학    과학   소속
A  60  84  80  70.0  문예부
B  77  62  95  85.0  과학부
D  75  65  95   NaN  다도부

In [45]:
b1

['문예부', '과학부', '다도부']

In [46]:
df["소속"].isin(b1) # 속하면 true, 속하지 않으면 false

A     True
B     True
C    False
D     True
Name: 소속, dtype: bool